package TEXT.runtime;

/*Generated by MPS */


public class Ruleset {
  public static void main(String[] args) {
    String result = "temp";
    System.out.println(result);
  }

  public static String S() {
    String[] stringArray = {<!TextGen not found for 'TEXT.structure.NonTerminal'!>};
    return "test";
  }
  public static String A() {
    String[] stringArray = {<!TextGen not found for 'TEXT.structure.Terminal'!>, <!TextGen not found for 'TEXT.structure.NonTerminal'!>};
    return "test";
  }
  public static String B() {
    String[] stringArray = {<!TextGen not found for 'TEXT.structure.Terminal'!>};
    return "test";
  }
}
