package TEXT.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SequenceTypes extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SequenceTypes() {
    super(0x3081af84875b46f6L, 0xbdd6db0e8277a296L, 0x1c80bcf267d372a6L, "SequenceTypes", "r:d3544938-0597-4a20-adba-4dc9a199f25b(TEXT.structure)/2053849179390964390");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_ZERO_OR_MORE_0 = new EnumerationDescriptor.MemberDescriptor("ZERO_OR_MORE", "*", 0x1c80bcf267d372a7L, "r:d3544938-0597-4a20-adba-4dc9a199f25b(TEXT.structure)/2053849179390964391");
  private final EnumerationDescriptor.MemberDescriptor myMember_ONE_OR_MORE_0 = new EnumerationDescriptor.MemberDescriptor("ONE_OR_MORE", "+", 0x1c80bcf267d372a8L, "r:d3544938-0597-4a20-adba-4dc9a199f25b(TEXT.structure)/2053849179390964392");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3081af84875b46f6L, 0xbdd6db0e8277a296L, 0x1c80bcf267d372a6L, 0x1c80bcf267d372a7L, 0x1c80bcf267d372a8L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_ZERO_OR_MORE_0, myMember_ONE_OR_MORE_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_ZERO_OR_MORE_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "ZERO_OR_MORE":
        return myMember_ZERO_OR_MORE_0;
      case "ONE_OR_MORE":
        return myMember_ONE_OR_MORE_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
