package TEXT.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int GrammarRule = 0;
  public static final int NonTerminal = 1;
  public static final int Production = 2;
  public static final int Terminal = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x3081af84875b46f6L, 0xbdd6db0e8277a296L);
    builder.put(0x1c80bcf267b85c1fL, GrammarRule);
    builder.put(0x1c80bcf267b85c28L, NonTerminal);
    builder.put(0x1c80bcf267b85c22L, Production);
    builder.put(0x1c80bcf267b85c25L, Terminal);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
