package TEXT.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class NonTerminal_Constraints extends BaseConstraintsDescriptor {
  public NonTerminal_Constraints() {
    super(CONCEPTS.NonTerminal$ta);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept NonTerminal$ta = MetaAdapterFactory.getConcept(0x3081af84875b46f6L, 0xbdd6db0e8277a296L, 0x1c80bcf267b85c28L, "TEXT.structure.NonTerminal");
  }
}
